on: push
name: Build / Test / Clippy
env:
  RUSTFLAGS: "-Dwarnings" # Make sure CI fails on all warnings
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy --all-targets --all-features
